[CI] Fixes (#245)
- Proper windows error handling
- Fix windows docker proxies
- Use more specific runner labels to enable experimentation with gfx-small runners
- Indicate docker login failure

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -15,7 +15,7 @@ env:
 
 jobs:
   cherry-pick-upstream:
-    runs-on: [self-hosted, linux]
+    runs-on: [self-hosted, linux, onecloud]
     if: github.ref == 'refs/heads/master' && github.event_name == 'push' && !startsWith(github.event.head_commit.message, '[CI]')
     steps:
     - uses: actions/checkout@v2
@@ -34,8 +34,9 @@ jobs:
 # LINUX CI
 
   build-linux:
-    runs-on: [self-hosted, linux]
+    runs-on: [self-hosted, linux, onecloud]
     strategy:
+      fail-fast: false
       matrix:
         include:
           - BUILD_PLATFORM: ubuntu-bionic
@@ -78,6 +79,10 @@ jobs:
               sleep 1
           done
           set -e
+          if [ "$retries" -eq 3 ]; then
+              echo "Registry login failed"
+              exit 1
+          fi
 
           docker build \
             --build-arg http_proxy \
@@ -174,7 +179,7 @@ jobs:
 
 # After the build is complete, if all CI publishing is complete, then we need to add the new test items to GTA.
   GTA-Test-Item-Publishing:
-    runs-on: [self-hosted, linux]
+    runs-on: [self-hosted, linux, onecloud]
     needs: [build-linux, build-windows, deploy-legacygta]
     if: github.ref == 'refs/heads/master'
     steps:
@@ -218,7 +223,7 @@ jobs:
       - name: Build tests
         run: |
           $env:BUILD_IMAGE = "ci-" + $env:GITHUB_REPOSITORY + "-windows"
-          cat .github/docker/build-windows.Dockerfile | docker build --build-arg ${env:http_proxy} --build-arg ${env:https_proxy} --build-arg VS_PRODUCT_KEY="${{ secrets.LZ_VS_PRODUCT_KEY }}" --build-arg VS_EDITION="${{ secrets.LZ_VS_EDITION }}" -t ${env:BUILD_IMAGE}:${env:GITHUB_RUN_ID} -
+          cat .github/docker/build-windows.Dockerfile | docker build --build-arg http_proxy --build-arg https_proxy --build-arg VS_PRODUCT_KEY="${{ secrets.LZ_VS_PRODUCT_KEY }}" --build-arg VS_EDITION="${{ secrets.LZ_VS_EDITION }}" -t ${env:BUILD_IMAGE}:${env:GITHUB_RUN_ID} -
 
           dt asset download --root-url https://gfx-assets.fm.intel.com/artifactory --dest-dir ./level-zero ${env:LZ_DEPLOY_ARTIFACTORY_PREFIX}/level-zero/master/windows/install level-zero
 
@@ -227,7 +232,9 @@ jobs:
           Foreach ($type in $tests)
           {
             docker run --rm -v ${pwd}:C:\project -w C:\project\build -e CC=clcache -e CXX=clcache ${env:BUILD_IMAGE}:${env:GITHUB_RUN_ID} cmake -G Ninja -D REQUIRE_OPENCL_BENCHMARKS=yes -D GROUP="/${type}_tests" -D CMAKE_PREFIX_PATH="/boost;/zlib;/libpng;/opencl;C:\project\level-zero" -D CMAKE_BUILD_TYPE=Release -D CMAKE_INSTALL_PREFIX=C:\project\level-zero-tests-${type} C:\project
+            if (!$?) { exit 1 }
             docker run --rm -v ${pwd}:C:\project -w C:\project\build -v C:\clcache-lz_tests:C:\clcache -e CLCACHE_DIR=C:\clcache ${env:BUILD_IMAGE}:${env:GITHUB_RUN_ID} cmake --build . --target install
+            if (!$?) { exit 1 }
 
             docker create --name ${env:GITHUB_RUN_ID} ${env:BUILD_IMAGE}:${env:GITHUB_RUN_ID}
             docker cp ${env:GITHUB_RUN_ID}:C:\libpng\bin\libpng16.dll .\level-zero-tests-${type}
